### PR TITLE
fix translation on header fields

### LINKED ISSUE #417: translation not working on fields placeholders
Changing the language should also be changing the placeholders text

Screenshot from 2020-07-13 21-53-28

### PR DESCRIPTION
**Pull request by pjcsouza**
Fixes #417

### CODE REVIEW

File: webapp/src/Builder/Builder.js [hunk 1]
```diff
@@ -186,6 +186,7 @@ class Builder extends Component {
     if (aux.header[event.target.name] === '') {
       delete aux.header[event.target.name];
     }
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/Builder.js:189]: please remove this line

File: webapp/src/Builder/CvHeaderField/index.js [hunk 2]
```diff
@@ -12,7 +12,7 @@ class CvHeaderField extends Component {
         <Form.Label column sm="2">
           {capitalize(this.props.label)}
           {this.props.mandatory ? ` (${translate('required')})` : ''}
-          :
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/CvHeaderField/index.js:15]: remove this change, this is actually part of the expected string

File: webapp/src/Builder/headerFields.js [hunk 3]
```diff
@@ -1,30 +1,39 @@
...
-  {
-    label: translate('birthday'), id: 'birthday', mandatory: false, placeholder: translate('date_format'),
-  },
-  {
-    label: translate('address'), id: 'address', mandatory: false, placeholder: translate('address_placeholder'),
-  },
-];
-
-export default headerFields;
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:3]: remove extra line

File: webapp/src/Builder/headerFields.js [hunk 4]
```diff
@@ -1,30 +1,39 @@
...
+export let headerFields = []
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:5]: ditto

File: webapp/src/Builder/headerFields.js [hunk 5]
```diff
@@ -1,30 +1,39 @@
...
+
+export function updateHeaderFields(){
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:8]: dittp

File: webapp/src/Builder/headerFields.js [hunk 6]
```diff
@@ -1,30 +1,39 @@
...
+      label: translate('birthday'), id: 'birthday', mandatory: false, placeholder: translate('date_format'),
+    },
+    {
+      label: translate('address'), id: 'address', mandatory: false, placeholder: translate('address_placeholder'),
+    },
+  ];
+
+}
+
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:38]: ditto

File: webapp/src/Builder/headerFields.js [hunk 7]
```diff
@@ -1,30 +1,39 @@
...
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:39]: ditto

File: webapp/src/Builder/Builder.js [hunk 8]
```diff
@@ -185,7 +185,7 @@ class Builder extends Component {
     aux.header[event.target.name] = event.target.value;
     if (aux.header[event.target.name] === '') {
       delete aux.header[event.target.name];
-    }
+    }
```
Comment (ramonsaboya) [inline webapp/src/Builder/Builder.js:188]: remove trailling spaces

File: webapp/src/Builder/headerFields.js [hunk 9]
```diff
@@ -1,30 +1,31 @@
...
-  {
-    label: translate('birthday'), id: 'birthday', mandatory: false, placeholder: translate('date_format'),
-  },
-  {
-    label: translate('address'), id: 'address', mandatory: false, placeholder: translate('address_placeholder'),
-  },
-];
-
-export default headerFields;
+export let headerFields = []
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:3]: it's okay to leave one blank line between functions/vars/etc, my comment was regarding leaving two instead of one

File: webapp/src/Builder/headerFields.js [hunk 10]
```diff
@@ -1,30 +1,31 @@
...
+      label: translate('phone'), id: 'phone', mandatory: false, placeholder: translate('phone_placeholder'),
+    },
+    {
+      label: translate('birthday'), id: 'birthday', mandatory: false, placeholder: translate('date_format'),
+    },
+    {
+      label: translate('address'), id: 'address', mandatory: false, placeholder: translate('address_placeholder'),
+    },
+  ];
+}
```
Comment (ramonsaboya) [inline webapp/src/Builder/headerFields.js:31]: always leave a single empty line at the end of the file

File: webapp/src/Builder/Builder.js [hunk 11]
```diff
@@ -188,7 +188,7 @@ class Builder extends Component {
     }
     this.setCv(aux);
   }
-
+
```
Comment (ramonsaboya) [inline webapp/src/Builder/Builder.js:191]: you have some extra spaces here hahaha
